app/uk/gov/hmrc/nrsretrievalfrontend/config/AppConfig.scala
app/uk/gov/hmrc/nrsretrievalfrontend/config/WSHttp.scala
app/uk/gov/hmrc/nrsretrievalfrontend/connectors/NrsRetrievalConnector.scala
app/uk/gov/hmrc/nrsretrievalfrontend/controllers/HelloWorld.scala
app/uk/gov/hmrc/nrsretrievalfrontend/views/error_template.scala.html
app/uk/gov/hmrc/nrsretrievalfrontend/views/govuk_wrapper.scala.html
app/uk/gov/hmrc/nrsretrievalfrontend/views/hello_world.scala.html
app/uk/gov/hmrc/nrsretrievalfrontend/views/main_template.scala.html
conf/application.conf
conf/prod.routes
project/FrontendBuild.scala
project/MicroService.scala
project/plugins.sbt
scalastyle-config.xml
test/uk/gov/hmrc/nrsretrievalfrontend/controllers/HelloWorldControllerSpec.scala

Added config for nrs retrieval

[NONPR-365] Create microservice for calling NRS Retrieval API

---

README.md

Updated readme to reflect initial status.

[NONPR-365] Create microservice for calling NRS Retrieval 

---

project/FrontendBuild.scala

[NONPR-162] Authenticate test users of the Nonrep Retrieval UI using Stride Auth stub [MDTP-UI]

---

app/config/AppConfig.scala
app/controllers/SearchController.scala
app/controllers/StartController.scala
conf/application.conf
test/controllers/SearchControllerControllerSpec.scala

Extended behaviour to pass X-API-Key header

[NONPR-450] Store Encrypted X-API-Key in DevOps Secrets Vault

---

app/Module.scala
app/actors/ActorService.scala
app/actors/CheckStatusActor.scala
app/actors/PollingActor.scala
app/actors/RetrievalActor.scala
app/models/NrsSearch.scala
app/models/SearchResult.scala
test/actors/RetrievalActorSpec.scala

Modified models to match api implementation

[NONPR-163] Integrate front-end Nonrep Retrieval UI to NRS Retrieval API microservice

---

app/Module.scala
app/actors/ActorMessage.scala
app/actors/RetrievalActor.scala
app/config/Auditable.scala
app/config/WSHttp.scala
app/connectors/NrsRetrievalConnector.scala
app/controllers/SearchController.scala
app/models/audit/DataEventAuditType.scala
test/actors/RetrievalActorSpec.scala
test/config/AuditableSpec.scala
test/connectors/NrsRetrievalConnectorSpec.scala

Added auditing to backend calls

[NONPR-205] Generate TxM explicit audit events from Retrieval UI [MDTP-UI]

---

conf/messages

Add "Search the" to the service title.

Update Display Name to "Search the Non-Repudiation Store" for GDS standard

---

app/models/audit/DataEventAuditType.scala

Change audit message from vatReturnVRN to VRN.

[NONPR-205] Generate TxM explicit audit events from Retrieval UI

---

README.md

[NONPR-379] Authenticate users of the Nonrep Retrieval UI using Stride Auth in Prod

---

README.md
app/assets/javascripts/download.js

[NONPR-513] Create README in nonrep-retrieval services repo

---

app/actors/ActorMessage.scala
app/actors/ActorService.scala
app/actors/CheckStatusActor.scala
app/actors/PollingActor.scala
app/actors/RetrievalActor.scala
app/assets/javascripts/download.js
app/config/AppConfig.scala
app/controllers/FormMappings.scala
app/controllers/SearchController.scala
app/models/CompletionStatus.scala
app/models/SearchPageAction.scala
app/models/SearchResult.scala
app/views/search_page.scala.html
app/views/search_query.scala.html
app/views/search_result.scala.html
app/views/search_result_retrieval_complete.scala.html
app/views/search_result_retrieval_failed.scala.html
app/views/search_result_retrieval_in_progress.scala.html
app/views/search_result_show.scala.html
app/views/search_results.scala.html
conf/app.routes
conf/application.conf
test/actors/PollingActorSpec.scala
test/actors/RetrievalActorSpec.scala
test/actors/StatusCheckActorSpec.scala
test/controllers/SearchControllerControllerSpec.scala
test/support/fixtures/SearchFixture.scala
test/views/search_pageSpec.scala

[NONPR-448] Automate polling and update of Search page on request retrieval of Submission Record

---

app/views/helpers/beta_banner.scala.html

[NONPR-559] Display correct auth user details in Retrieval UI

---

app/models/ServiceScope.scala

Removed resolved todo comment.

[NONPR-522] Make the call to action to Retrieve/Download the Submission Record unique 

---

app/models/SearchResult.scala
app/views/search_result_retrieval_complete.scala.html
app/views/search_result_retrieval_failed.scala.html
app/views/search_result_retrieval_in_progress.scala.html
app/views/search_result_show.scala.html
conf/messages
test/model/SearchTest.scala

Added missing "submitted" text

[NONPR-522] Make the call to action to Retrieve/Download the Submission Record unique

---

app/config/AppConfig.scala
app/views/govuk_wrapper.scala.html
app/views/helpers/Utils.scala
app/views/helpers/govuk_template.scala.html
app/views/search_query.scala.html
app/views/service_scope.scala.html

[NONPR-488] UX Enhancements to Go-Live experience

---

app/controllers/SearchController.scala
app/views/govuk_wrapper.scala.html

Correct wording on locally failing errors.

[NONPR-560] Show error page if query or retrieve functionality is unavailable

---

conf/application.conf
test/resources/application.conf

Default stride status enabled.

[NONPR-582] Set up Jenkins jobs to run MDTP Retrieval UI tests

---

app/config/AppConfig.scala

[NONPR-492]

---

app/actors/CheckStatusActor.scala
app/actors/PollingActor.scala
app/actors/RetrievalActor.scala
app/controllers/SearchController.scala
app/controllers/SelectorController.scala
app/controllers/StartController.scala
app/controllers/Stride.scala

Added logging to aid resolution of gateway timeouts.

[NONPR-675]

---

project/plugins.sbt

Update version of sassify to a less broken one

[NONPR-834] Migrate NRS MDTP Services to 'New Build'

---

conf/application.conf
test/support/fixtures/NrsSearchFixture.scala

Removes CDS config.
Also fix for type in headerData test. All tests pass:
```
[info] Passed: Total 53, Failed 0, Errors 0, Passed 53
```

NONPR-1888 Removes CDS config

---

conf/application.conf

[NONPR-1887] Example ITSA notable event config added for demo purposes

---

.bsp/sbt.json
.gitignore
build.sbt
project/build.properties
project/plugins.sbt
test/actors/PollingActorSpec.scala
test/actors/RetrievalActorSpec.scala
test/actors/StatusCheckActorSpec.scala
test/config/AuditableSpec.scala
test/connectors/NrsRetrievalConnectorSpec.scala
test/controllers/SearchControllerControllerSpec.scala
test/support/BaseSpec.scala
test/support/fixtures/Infrastructure.scala
test/support/fixtures/StrideFixture.scala

**Acceptance-tests results:** 
- 24 Scenarios (24 passed)
- 196 Steps (196 passed)
- Runtime: 4m1.908s
**Tests Results:** 
- [info] Run completed in 11 seconds, 86 milliseconds.
- [info] Total number of tests run: 53
- [info] Suites: completed 13, aborted 0
- [info] Tests: succeeded 53, failed 0, canceled 0, ignored 0, pending 0
- [info] All tests passed.
- [info] Passed: Total 53, Failed 0, Errors 0, Passed 53

Nonpr 1717 upgrades

---

build.sbt
project/plugins.sbt

**Acceptance Tests**
- 24 Scenarios (24 passed)
- 196 Steps (196 passed)
- 1m31.374s
- Total time: 104 s, completed 21 May 2021, 12:39:18
**Unit Tests**
- All tests passed.
- [info] Passed: Total 53, Failed 0, Errors 0, Passed 53
- [success] Total time: 16 s, completed 21 May 2021, 12:35:40
Build seem to be stable with the current upgrades, have added a new 'Akka-testkit' to support crashing unit tests, which has been successful.

NONPR-1717-upgraded bootstrap to play-27 and uplifted akka-packages to support tests 

---

build.sbt

**Acceptance Tests**
- 24 Scenarios (24 passed)
- 196 Steps (196 passed)
- 3m56.912s
- Passed: Total 186, Failed 0, Errors 0, Passed 186
- [success] Total time: 249 s, completed 24 May 2021, 12:13:27
**Unit Tests**
- [info] Tests: succeeded 53, failed 0, canceled 0, ignored 0, pending 0
- [info] All tests passed.
- [info] Passed: Total 53, Failed 0, Errors 0, Passed 53
- [success] Total time: 12 s, completed 24 May 2021, 12:57:14

NONPR-1718-Cleaned-up and updated govuk-template

---

project/plugins.sbt

**it-tests Result**
- [info] All tests passed.
- [info] Passed: Total 21, Failed 0, Errors 0, Passed 21
- [success] Total time: 21 s, completed 10 Jun 2021, 11:33:14
**Test Result**
- [info] All tests passed.
- [info] Passed: Total 53, Failed 0, Errors 0, Passed 53
- [success] Total time: 13 s, completed 10 Jun 2021, 11:35:35
**Acceptance Tests Result**
- 24 Scenarios (24 passed)
- 196 Steps (196 passed)
- 4m12.280s
- [info] Passed: Total 186, Failed 0, Errors 0, Passed 186
- [success] Total time: 267 s, completed 10 Jun 2021, 11:49:09

NONPR-1717-upgraded major behind version sbt-artifactory

---

.gitignore
build.sbt
project/build.properties
project/plugins.sbt
test/actors/PollingActorSpec.scala
test/actors/RetrievalActorSpec.scala
test/actors/StatusCheckActorSpec.scala
test/config/AuditableSpec.scala
test/connectors/NrsRetrievalConnectorSpec.scala
test/controllers/SearchControllerControllerSpec.scala
test/support/BaseSpec.scala
test/support/fixtures/Infrastructure.scala
test/support/fixtures/StrideFixture.scala

So that I can build it locally!
Download working successfully in Dev with Chrome when 0.76.0 deployed.
```
sbt test
...
[info] ScalaTest
[info] Run completed in 12 seconds, 117 milliseconds.
[info] Total number of tests run: 53
[info] Suites: completed 13, aborted 0
[info] Tests: succeeded 53, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 53, Failed 0, Errors 0, Passed 53
[success] Total time: 26 s, completed 01-Jul-2021 16:38:39
```
acceptance tests:
```
[info] ScalaTest
[info] Run completed in 3 minutes, 17 seconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Passed: Total 24, Failed 0, Errors 0, Passed 24 …
```

[NONPR-2134] make master the same as 0-76-0 tag

---

app/connectors/NrsRetrievalConnectorImpl.scala
app/controllers/SearchController.scala
build.sbt
it/uk/gov/hmrc/nrsretrievalfrontend/IntegrationSpec.scala
it/uk/gov/hmrc/nrsretrievalfrontend/XApiHeaderIntegrationSpec.scala
it/uk/gov/hmrc/nrsretrievalfrontend/connectors/NrsRetrievalContractSpec.scala
it/uk/gov/hmrc/nrsretrievalfrontend/stubs/NrsRetrievalStubs.scala
it/uk/gov/hmrc/nrsretrievalfrontend/wiremock/WireMockSupport.scala

```
sbt test
...
[info] ScalaTest
[info] Run completed in 11 seconds, 230 milliseconds.
[info] Total number of tests run: 55
[info] Suites: completed 13, aborted 0
[info] Tests: succeeded 55, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 55, Failed 0, Errors 0, Passed 55
[success] Total time: 24 s, completed 05-Jul-2021 11:44:49
```
```
set it:test 
...
[info] ScalaTest
[info] Run completed in 20 seconds, 358 milliseconds.
[info] Total number of tests run: 21
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 21, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 21, Failed 0, Errors 0, Passed 21
[success] Total time: 23 s, completed 05-Jul-2021 11:46:58
```
acceptance-tests
```
[info] ScalaTest …
```

[NONPR-2134] add diagnostic logging and integration tests

---

conf/application.conf
test/controllers/SearchControllerControllerSpec.scala

[info] Passed: Total 57, Failed 0, Errors 0, Passed 57
[success] Total time: 27 s, completed 8 Jul 2021, 13:06:03
Acceptance Tests:
[info] Passed: Total 27, Failed 0, Errors 0, Passed 27
[success] Total time: 340 s (05:40), completed 8 Jul 2021, 15:17:08

NONPR-2106-Added PPT notable event to app.conf and added search tests

---

conf/application.conf
test/config/AppConfigSpec.scala

```
[info] Run completed in 14 seconds, 968 milliseconds.
[info] Total number of tests run: 170
[info] Suites: completed 21, aborted 0
[info] Tests: succeeded 170, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 170, Failed 0, Errors 0, Passed 170
[success] Total time: 30 s, completed 27 Sep 2021, 14:10:36
```

Nonpr 2242

---

app/assets/javascripts/nrs.js
app/config/AppConfig.scala
app/views/components/Button.scala.html
app/views/components/Heading1.scala.html
app/views/components/Layout.scala.html
app/views/components/Paragraph.scala.html
app/views/components/SearchResultPanel.scala.html
app/views/components/SearchResultsPanel.scala.html
app/views/components/TextInput.scala.html
app/views/error_template.scala.html
app/views/search_page.scala.html
app/views/selector_page.scala.html
app/views/start_page.scala.html
app/views/testonly/check_authorisation_page.scala.html
app/views/testonly/validate_download_page.scala.html
build.sbt
conf/application.conf
project/plugins.sbt

To be merged along with https://github.com/hmrc/nrs-retrieval-acceptance-tests/pull/68
```
sbt test
...
[info] Run completed in 20 seconds, 276 milliseconds.
[info] Total number of tests run: 236
[info] Suites: completed 21, aborted 0
[info] Tests: succeeded 236, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 236, Failed 0, Errors 0, Passed 236
[success] Total time: 70 s (01:10), completed 4 Apr 2022, 09:29:23
```
```
sbt it:test
...
[info] ScalaTest
[info] Run completed in 27 seconds, 760 milliseconds.
[info] Total number of tests run: 41
[info] Suites: completed 4, aborted 0
[info] Tests: succeeded 41, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 41, Failed 0, Errors 0, Passed 41
[success] Total time: …
```

Nonpr 2362 no jquery

---

app/actors/ActorService.scala
build.sbt

```
sbt test
...
[info] ScalaTest
[info] Run completed in 15 seconds, 416 milliseconds.
[info] Total number of tests run: 185
[info] Suites: completed 22, aborted 0
[info] Tests: succeeded 185, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 185, Failed 0, Errors 0, Passed 185
[success] Total time: 17 s, completed 5 May 2022, 08:06:59
```
```
sbt it:test
...
[info] ScalaTest
[info] Run completed in 28 seconds, 687 milliseconds.
[info] Total number of tests run: 41
[info] Suites: completed 4, aborted 0
[info] Tests: succeeded 41, failed 0, canceled 0, ignored 0, pending 0
[info] Passed: Total 41, Failed 0, Errors 0, Passed 41
[success] Total time: 30 s, completed 5 May 2022, 08:08:14
```
acceptance test run
```
[info] …
```

upgrade bootstrap-frontend-play-28

---

conf/application.conf
test/config/AppConfigSpec.scala

Adds new notable event for ppt-return.
```
[info] Run completed in 12 seconds, 969 milliseconds.
[info] Total number of tests run: 193
[info] Suites: completed 22, aborted 0
[info] Tests: succeeded 193, failed 0, canceled 0, ignored 0, pending 0
```

NONPR-2635 Add 1 Notable event to the NRS service - PPT

---

conf/application.conf
project/plugins.sbt
test/config/AppConfigSpec.scala

NONPR-3205: Extend NRS Retrieval UI with EMCS notable event - Create a movement UI

---

app/assets/javascripts/nrs.js
app/uk/gov/hmrc/nrsretrievalfrontend/controllers/SearchController.scala
app/uk/gov/hmrc/nrsretrievalfrontend/views/components/SearchResultPanel.scala.html
app/uk/gov/hmrc/nrsretrievalfrontend/views/search_page.scala.html
conf/app.routes
it/test/uk/gov/hmrc/nrsretrievalfrontend/Fixture.scala
it/test/uk/gov/hmrc/nrsretrievalfrontend/NrsRetrievalIntegrationSpec.scala
test/uk/gov/hmrc/nrsretrievalfrontend/controllers/SearchControllerSpec.scala

NONPR-3350: Add notable event mdc context to retrieve and download requests

---

app/uk/gov/hmrc/nrsretrievalfrontend/connectors/NrsRetrievalConnectorImpl.scala
app/uk/gov/hmrc/nrsretrievalfrontend/controllers/SearchController.scala
app/uk/gov/hmrc/nrsretrievalfrontend/http/HttpGetRaw.scala
app/uk/gov/hmrc/nrsretrievalfrontend/http/HttpHead.scala

NONPR-3350: Explicitly adding notable event mdc context to download requests
